### ISSUE TITLE
Error after Syntastic closes location list in Vim ~ 8.1.0118

### ISSUE THREAD

**Issue by nattofriends** [blueyed/vim-qf_resize#15]
Hi,

qf_resize seems to have an issue in Vim 8.1.0118, but not in 8.0.1418. (Sorry I don't know the version where this became an issue.)

I am using qf_resize with Syntastic, and after Syntastic checks a file that previously had errors but no longer does (so the location list is closed), the following error message is shown:

```
Error detected while processing function qf_resize#adjust_window_height[19]..<SNR>59_get_nonfixed_above:
line    8:
E16: Invalid range: keepalt noautocmd 2 wincmd w
```

**Comment by blueyed** [comment]
Thanks for the report, I could bisect this myself (one of my recent hobbies ;)), but wonder if/why https://github.com/blueyed/vim-qf_resize/issues/5 isn't an issue then already for you?

btw: you might want to try Neomake instead of Syntastic.. :)

**Comment by nattofriends** [comment]
It might have also been #5 (for reasons, I used a bunch of different Vim versions lately) but I figured the error message was different so I reported it here.

**Comment by blueyed** [comment]
Re #5: there is a workaround for patch-8.0.0677, which I have forgotten about.

I assume this is still reproducible for you?

**Comment by nattofriends** [comment]
Yes, it is.

**Comment by blueyed** [comment]
Ah.  I think the workaround for #5 that gets automatically used with newer Vims causes this for you.

https://github.com/blueyed/vim-qf_resize/pull/16 should fix it.

**Comment by nattofriends** [comment]
Thanks!
