### ISSUE TITLE
Broken in Vim v8.0.0677+ 

### ISSUE THREAD

**Issue by blueyed** [blueyed/vim-qf_resize#5]
https://github.com/vim/vim/issues/1839

**Comment by blueyed** [comment]
Now (reporting) users are affected: https://github.com/blueyed/vim-qf_resize/issues/8.

Need to find a fix/workaround I guess.

**Comment by mgedmin** [comment]
The following workaround works for me in `ftplugin/qf.vim` with Vim 8.0.1330:

```
" Shrink too-high quickfix windows
if winheight(0) > line('$')
  exe "resize" line('$')
endif
```

**Comment by blueyed** [comment]
Thanks for reminding me, https://github.com/blueyed/vim-qf_resize/pull/10 should fix it hopefully for Vim.

**Comment by blueyed** [comment]
Well, it is a bit more complicated though - I will need to fix this further..

I will consider using a ftplugin with `resize` directly in there for simplicity.
The problem however is that it is not allowed to look at other windows using `wincmd` from there, but at least for Neovim there is an API (`nvim_win_get_position`) that can be used instead.  And for Vim we could track the information in another way maybe.

**Comment by blueyed** [comment]
The patch(es) landed in Neovim now: https://github.com/neovim/neovim/pull/8645.

**Comment by blueyed** [comment]
For Neovim `nvim_win_get_position` could be used probably.

**Comment by blueyed** [comment]
Oh, there is `g:qf_resize_use_feedkeys`, which works around this.

For the Neovim development version you have to forcefully set it currently, since the `has('patch-8.0.0677')` check still returns 0.
