### ISSUE TITLE
Error when combined with lervag/vimtex

### ISSUE THREAD

**Issue by doronbehar** [blueyed/vim-qf_resize#8]
I use the package [`vimtex`](https://github.com/lervag/vimtex)  by @lervag and I use the key mapping `<localleader>le` to open Tex compilation errors in the Quickfix window. If I have `vim-qf_resize` installed and hit these keys, I get the following error:
```
Error detected while processing function <SNR>79_adjust_window_height[19]..<SNR>79_get_nonfixed_in_dir:
line    6:
E788: Not allowed to edit another buffer now
Error detected while processing function vimtex#qf#toggle[4]..vimtex#qf#open:
line   31:
E171: Missing :endif
Error detected while processing function vimtex#qf#toggle:
line    4:
E171: Missing :endif
```

Is there any workaround?
Thanks.

**Comment by blueyed** [comment]
Seems like this is https://github.com/blueyed/vim-qf_resize/issues/5.

**Comment by blueyed** [comment]
The workaround would be to use Neovim for now.. ;)

**Comment by doronbehar** [comment]
I usually use Neovim but I'm still waiting for https://github.com/neovim/neovim/issues/7200 to appear in the next release.
Thanks.
